allowBuilds:
  '@parcel/watcher': true
  '@scarf/scarf': false
  '@swc/core': true
  '@tree-sitter-grammars/tree-sitter-yaml': false
  core-js-pure: false
  esbuild: true
  tree-sitter: false
  tree-sitter-json: false
minimumReleaseAgeExclude:
  - '@dracor/react@1.4.0'
