allowBuilds:
  '@parcel/watcher': true
  '@scarf/scarf': set this to true or false
  '@swc/core': true
  '@tree-sitter-grammars/tree-sitter-yaml': set this to true or false
  core-js-pure: set this to true or false
  esbuild: true
  tree-sitter: set this to true or false
  tree-sitter-json: set this to true or false
minimumReleaseAgeExclude:
  - '@dracor/react@1.4.0'
