/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as PlaysRouteImport } from './routes/plays'
import { Route as IdIdRouteImport } from './routes/id/$id'
import { Route as OriginalsIndexRouteImport } from './routes/originals/index'
import { Route as OriginalsSlugRouteImport } from './routes/originals/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaysRoute = PlaysRouteImport.update({
  id: '/plays',
  path: '/plays',
  getParentRoute: () => rootRouteImport,
} as any)
const IdIdRoute = IdIdRouteImport.update({
  id: '/id/$id',
  path: '/id/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OriginalsIndexRoute = OriginalsIndexRouteImport.update({
  id: '/originals/',
  path: '/originals/',
  getParentRoute: () => rootRouteImport,
} as any)
const OriginalsSlugRoute = OriginalsSlugRouteImport.update({
  id: '/originals/$slug',
  path: '/originals/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/locations': typeof LocationsRoute
  '/plays': typeof PlaysRoute
  '/id/$id': typeof IdIdRoute
  '/originals/$slug': typeof OriginalsSlugRoute
  '/originals/': typeof OriginalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/locations': typeof LocationsRoute
  '/plays': typeof PlaysRoute
  '/id/$id': typeof IdIdRoute
  '/originals/$slug': typeof OriginalsSlugRoute
  '/originals': typeof OriginalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/locations': typeof LocationsRoute
  '/plays': typeof PlaysRoute
  '/id/$id': typeof IdIdRoute
  '/originals/$slug': typeof OriginalsSlugRoute
  '/originals/': typeof OriginalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/about'
    | '/locations'
    | '/plays'
    | '/id/$id'
    | '/originals/$slug'
    | '/originals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/about'
    | '/locations'
    | '/plays'
    | '/id/$id'
    | '/originals/$slug'
    | '/originals'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/about'
    | '/locations'
    | '/plays'
    | '/id/$id'
    | '/originals/$slug'
    | '/originals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AboutRoute: typeof AboutRoute
  LocationsRoute: typeof LocationsRoute
  PlaysRoute: typeof PlaysRoute
  IdIdRoute: typeof IdIdRoute
  OriginalsSlugRoute: typeof OriginalsSlugRoute
  OriginalsIndexRoute: typeof OriginalsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plays': {
      id: '/plays'
      path: '/plays'
      fullPath: '/plays'
      preLoaderRoute: typeof PlaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/id/$id': {
      id: '/id/$id'
      path: '/id/$id'
      fullPath: '/id/$id'
      preLoaderRoute: typeof IdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/originals/': {
      id: '/originals/'
      path: '/originals'
      fullPath: '/originals/'
      preLoaderRoute: typeof OriginalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/originals/$slug': {
      id: '/originals/$slug'
      path: '/originals/$slug'
      fullPath: '/originals/$slug'
      preLoaderRoute: typeof OriginalsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AboutRoute: AboutRoute,
  LocationsRoute: LocationsRoute,
  PlaysRoute: PlaysRoute,
  IdIdRoute: IdIdRoute,
  OriginalsSlugRoute: OriginalsSlugRoute,
  OriginalsIndexRoute: OriginalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
