name: Deploy to production

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  production:
    if: ${{ ! github.event.release.prerelease }}
    uses: dracor-org/einakter/.github/workflows/deployment.yml@main
    with:
      host: dracor.org
      deploy-path: /var/www/einakter
    secrets:
      deploy-key: ${{ secrets.DRACOR_ORG_DEPLOY_KEY }}
      deploy-user: ${{ secrets.DRACOR_ORG_DEPLOY_USER }}
