name: Deployment

on:
  workflow_call:
    inputs:
      host:
        required: true
        type: string
      deploy-path:
        required: true
        type: string
    secrets:
      deploy-key:
        required: true
      deploy-user:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-tags: true
          fetch-depth: 0
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "20.x"
      - name: Restore node_modules
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - run: yarn install
      - run: yarn test --watch=false
      - run: echo "VITE_VERSION=$(git describe --tags --dirty --always | sed s/^v// | sed s/-g/-/)" >> $GITHUB_ENV
      - run: echo $VITE_VERSION
      - run: yarn build

      - uses: webfactory/ssh-agent@dc588b651fe13675774614f8e6a936a468676387 # v0.9.0
        with:
          ssh-private-key: ${{ secrets.deploy-key }}

      - name: Deploy to ${{ inputs.host }}
        run: |
          rsync -rlvz --delete \
            --exclude=robots.txt \
            --exclude=google*.html \
            -e 'ssh -o StrictHostKeyChecking=no' \
            build/ \
            ${{ secrets.deploy-user }}@${{ inputs.host }}:${{ inputs.deploy-path }}/
