name: Deployment

on:
  workflow_call:
    inputs:
      host:
        required: true
        type: string
      deploy-path:
        required: true
        type: string
    secrets:
      deploy-key:
        required: true
      deploy-user:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Restore node_modules
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - run: pnpm install
      - run: pnpm test --watch=false
      - run: echo "VITE_VERSION=$(git describe --tags --dirty --always | sed s/^v// | sed s/-g/-/)" >> $GITHUB_ENV
      - run: echo $VITE_VERSION
      - run: pnpm build

      - uses: webfactory/ssh-agent@dc588b651fe13675774614f8e6a936a468676387 # v0.9.0
        with:
          ssh-private-key: ${{ secrets.deploy-key }}

      - name: Deploy to ${{ inputs.host }}
        run: |
          rsync -rlvz --delete \
            --exclude=robots.txt \
            --exclude=google*.html \
            -e 'ssh -o StrictHostKeyChecking=no' \
            build/ \
            ${{ secrets.deploy-user }}@${{ inputs.host }}:${{ inputs.deploy-path }}/
